version: "3.4"

# Run this one if you already have nginx and acme-companion running from Yukkuricraft/Yukkuricraft

services:
  yakumo-dash:
    container_name: yakumo-dash-${IMAGE_NAME_SUFFIX}
    image: yukkuricraft/yakumo-dash-${IMAGE_NAME_SUFFIX}
    environment:
      VIRTUAL_HOST: ${YAKUMO_HOST}
      VIRTUAL_PORT: ${YAKUMO_PORT}
      LETSENCRYPT_HOST: ${YAKUMO_HOST}
    volumes:
      - ./src:/app/src
    networks:
      - yukkuricraft_yc-web-dev
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "20"

networks:
  yukkuricraft_yc-web-dev:
    external: true
