version: "3.4"

services:
  yakumo-dash:
    container_name: yakumo-dash-dev
    image: yukkuricraft/yakumo-dash-dev
    command: yarn start
    environment:
      VIRTUAL_HOST: yakumo.yukkuricraft.net
      VIRTUAL_PORT: 25699
      LETSENCRYPT_HOST: yakumo.yukkuricraft.net
    volumes:
      - ./src:/app/src

  nginx-proxy:
    container_name: nginx-proxy-yakumo-dash
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d

  letsencrypt-nginx-proxy:
    container_name: letsencrypt-nginx-proxy-yakumo-dash
    image: nginxproxy/acme-companion
    environment:
      DEFAULT_EMAIL: remi@yukkuricraft.net
      ACME_CA_URI: https://acme-v02.api.letsencrypt.org/directory
      NGINX_PROXY_CONTAINER: nginx-proxy-yakumo-dash
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy

volumes:
  certs:
  html:
  vhost:
  acme:

